[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm turbo build --filter=@yantrix/web --concurrency=1"]

[start]
cmd = "sh -lc 'node apps/web/.next/standalone/server.js || node apps/web/.next/standalone/apps/web/server.js'"
